kumuluzee:
  name: ms-images
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
      - jndi-name: jdbc/RsobookDS
        connection-url: jdbc:postgresql://localhost:5432/rsobook-images
        username: postgres
        password: root
        max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
properties:
  maxsize: 500000
  storageapikey: nastimaj_si_env_variable
  storageinstanceid: nastimaj_si_env_variable
  storageendpoint: https://cos-service.bluemix.net/endpoints
  storagebucket: rsobook-images-eu
  storagelocation: eu
