kumuluzee:
  name: rsobook-image-microservice
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
      - jndi-name: jdbc/ImagesDS
        connection-url: jdbc:postgresql://localhost:5432/images
        username: dbuser
        password: postgres
        max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
properties:
  maxsize: 500000
  storageapikey: nastimaj_si_env_variable
  storageinstanceid: nastimaj_si_env_variable
  storageendpoint: https://cos-service.bluemix.net/endpoints
  storagebucket: rsobook-images-eu
  storagelocation: eu
