kumuluzee:
  name: ms-images
  env:
    name: dev
  version: 2.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
      - jndi-name: jdbc/RsobookDS
        connection-url: jdbc:postgresql://localhost:5432/rsobook-images
        username: postgres
        password: root
        max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: false
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/RsobookDS
      disk-space-health-check:
        threshold: 100000000
  metrics:
    generic-registry-name: default
    jvm:
      enabled: true
      registry-name: jvm
    servlet:
      enabled: true
      mapping: /metrics
    logs:
      enabled: true
      period-s: 30
      level: INFO
    web-instrumentation:
      - name: image-endpoint
        url-pattern: /api/v1/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="user">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <Socket name="logstash" host="f6944143-97cf-43e5-942c-0f607895adf0-ls.logit.io" port="14502" protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <AppenderRef ref="logstash" level="info"/>
                          </Root>
                      </Loggers>
                  </Configuration>'
properties:
  maxsize: 500000
  storageapikey: nastimaj_si_env_variable
  storageinstanceid: nastimaj_si_env_variable
  storageendpoint: https://s3.eu-geo.objectstorage.softlayer.net
  storagebucket: rsobook-images-eu
  storagelocation: eu-geo
