apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-images
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-images
    spec:
      containers:
      - image: rsobook/ms-images:2.0.3
        name: ms-images
        env:
          - name: PORT
            value: "80"
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://ms-etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://ms-etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://ms-database:5432/rsobook-images
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://10.126.123.38:32696
          - name: PROPERTIES_STORAGEAPIKEY
            value: "nepovem"
          - name: PROPERTIES_STORAGEINSTANCEID
            value: "nepovem"
        ports:
        - containerPort: 80
          name: server
          protocol: TCP