apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: microservice-images
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-images
    spec:
      containers:
      - image: rsobook/microservice-images
        name: microservice-images
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://microservice-etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://microservice-etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://microservice-database:5432/images
          - name: KUMULUZEE_SERVER_BASEURL
            value: kva_tle
          - name: PROPERTIES_STORAGEAPIKEY
            value: secret
          - name: PROPERTIES_STORAGEINSTANCEID
            value: secret
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP