apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ms-images
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-images
    spec:
      containers:
      - image: rsobook/ms-images:1.0.2
        name: ms-images
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://ms-etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://ms-etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://ms-database:5432/rsobook-images
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://10.126.123.38:32696
          - name: PROPERTIES_STORAGEAPIKEY
            value: 8WEP6C_HpWK05d8tVR8wcDJZ4YEpXoIuPzf064GfwU_9
          - name: PROPERTIES_STORAGEINSTANCEID
            value: "crn:v1:bluemix:public:cloud-object-storage:global:a/68aa4a3ebc6d45c593e585d3c4e8b258:f1a7204f-6d5e-4fc0-96d0-4da179cfeb84::"
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP